INSERT INTO SELLER(Name,Email,MobileNo,Address) VALUES('Keshav Bajaj','keshavb2712@gamil.com','8529778412','22 BAKER STREET, LONDON, EUROPE');
INSERT INTO SELLER(Name,Email,MobileNo,Address) VALUES('Mayank Jain','lala@dontcare.com','1234567890','4144  Edsel Road, Fullerton, CA, California');
INSERT INTO SELLER(Name,Email,MobileNo,Address) VALUES('Komal Goyal','KOMAL.GOYAL@YIPEE.COM','7147264158','2438  Timberbrook Lane Denver Colorado');
INSERT INTO SELLER(Name,Email,MobileNo,Address) VALUES('Crystal D Whetstone','4cctuaumwyu@temporarymail.net','9703001132','3550  Oak Ridge Drive Cape Girardeau Missouri');
INSERT INTO SELLER(Name,Email,MobileNo,Address) VALUES('Barbara R Koons','7atizuum56@temporarymail.net','3612861261','1101  Duff Avenue Brattleboro Vermont');
INSERT INTO SELLER(Name,Email,MobileNo,Address) VALUES('Mark S Davidson','sivot47109@javadoq.com','3612861161','1016  Boone Street Tivoli Texas');
INSERT INTO SELLER(Name,Email,MobileNo,Address) VALUES('Allan C Ignacio','sisdfasde@jasegaesq.com','4145734928','2148  Woodlawn Drive New Berlin Wisconsin');
INSERT INTO SELLER(Name,Email,MobileNo,Address) VALUES('Gautam  Banerjee','hnr76gibtxd@temporarymail.net','2224978989','Nr Ganga Jamuna Cinema, 220 Tardeo Road, Grant Road  Mumbai  Maharashtra');
INSERT INTO SELLER(Name,Email,MobileNo,Address) VALUES('Mallika  Patil','nvymitodwi@temporarymail.net','2652422189','Opp. A.s.motors Salatwada, Opp. A.s.motors, Salatwada, Opp. A.s.motors, Salatwada  Vadodara  Gujarat');
INSERT INTO SELLER(Name,Email,MobileNo,Address) VALUES('Raktavira  Varghese','kebpxg254u@lamo.net','0222500766','133 , A, Ghatkopar Indl Est, L.b. Shastri Marg, Op Amrut Nagar Rd, Ghatkopar (west)  Maharashtra');
INSERT INTO AGENT(Name,Salary,SuperId,MobileNo) VALUES('Varuna  Hans','320000',NULL,'8250762377');
INSERT INTO AGENT(Name,Salary,SuperId,MobileNo) VALUES('Arav  Kata','150000','1','4553352588');
INSERT INTO AGENT(Name,Salary,SuperId,MobileNo) VALUES('Zohar  Chatterjee','85000','2','9932631660');
INSERT INTO AGENT(Name,Salary,SuperId,MobileNo) VALUES('Sara  Handa','85000','2','4198051218');
INSERT INTO AGENT(Name,Salary,SuperId,MobileNo) VALUES('Amma  Oak','150000','1','8161464869');
INSERT INTO AGENT(Name,Salary,SuperId,MobileNo) VALUES('Jatin  Chandra','85000','5','8992307156');
INSERT INTO AGENT(Name,Salary,SuperId,MobileNo) VALUES('Ran  Balay','85000','5','7923841068');
INSERT INTO AGENT(Name,Salary,SuperId,MobileNo) VALUES('Kamana  Gopal','85000','5','8800704999');
INSERT INTO AGENT(Name,Salary,SuperId,MobileNo) VALUES('Archana  Pandit','85000','2','9562003990');
INSERT INTO AGENT(Name,Salary,SuperId,MobileNo) VALUES('Jaganmata  Kulkarni','85000','5','7764568872');
INSERT INTO BANK(Name,BranchAddress) VALUES('Metro Bank',' 1 Southampton Row, Holborn, London WC1B 5HA, United Kingdom');
INSERT INTO BANK(Name,BranchAddress) VALUES('Union Bank of India (UK) Ltd','Senator House, 85 Queen Victoria St, London EC4V 4AB, United Kingdom');
INSERT INTO BANK(Name,BranchAddress) VALUES('TurkishBank UK','84-86 Borough High St, London SE1 1LN, United Kingdom');
INSERT INTO BANK(Name,BranchAddress) VALUES('Metro Bank','120 Cheapside, London EC2V 7JB, United Kingdom');
INSERT INTO BANK(Name,BranchAddress) VALUES('Bank of China','107 Shaftesbury Ave, Soho, London W1D 5DA, United Kingdom');
INSERT INTO BANK(Name,BranchAddress) VALUES('Bank Sepah International PLC','5-7, Eastcheap, Bridge, London EC3M 1JT, United Kingdom');
INSERT INTO BANK(Name,BranchAddress) VALUES('Barclays Bank','120 Moorgate, Finsbury, London EC2M 6UR, United Kingdom');
INSERT INTO BANK(Name,BranchAddress) VALUES('Handelsbanken London Holborn Branch','2, 1 Kingsway, Holborn, London WC2B 6AN, United Kingdom');
INSERT INTO BANK(Name,BranchAddress) VALUES('Deutsche Bank','10 Bishops Square, Spitalfields, London E1 6EG, United Kingdom');
INSERT INTO BANK(Name,BranchAddress) VALUES('Handelsbanken London West End Branch','3, 86 Jermyn St, St. James, London SW1Y 6JD, United Kingdom');
INSERT INTO BUYER(Name,Email,MobileNo,Address,CreditScore,BankID) VALUES('Sia Cooley','petersko@msn.com','8870017519','G7 Mahalaxmi Ind Est, D C Rd, Delisle Road  Maharashtra','438','5');
INSERT INTO BUYER(Name,Email,MobileNo,Address,CreditScore,BankID) VALUES('Arianna Ahmed','rgiersig@live.com','7162917664','276  Savita Sadan, V P Road, st Parsiwada, Girgaum, Maharashtra','767','2');
INSERT INTO BUYER(Name,Email,MobileNo,Address,CreditScore,BankID) VALUES('Ioan Ball','hikoza@hotmail.com','8276304328','Shop No 2, Vijay Bhavan, Proctor Road, Grant Road  Maharashtra','671','1');
INSERT INTO BUYER(Name,Email,MobileNo,Address,CreditScore,BankID) VALUES('Amanda Bowen','weazelman@aol.com','6475472595','23 , Pancheel Heights, Mahavir Nagar, Opp Woodland Hotel, Kandivli(w) Delhi','752','8');
INSERT INTO BUYER(Name,Email,MobileNo,Address,CreditScore,BankID) VALUES('Virgil Chase','ahuillet@mac.com','6967217994','32 nd Floor, /, Jalan Bhavan, Kalbadevi Road, Badamwadi, Kalbadevi Patna','782','5');
INSERT INTO BUYER(Name,Email,MobileNo,Address,CreditScore,BankID) VALUES('Ishaq Dickerson','ehood@live.com','6549599252','Plot No 4 & 5, Yeshwant Smruti, Kalyan Road, Near Hotel Janki,gopal Nagar, Dombivli (east) Hyderbad','648','4');
INSERT INTO BUYER(Name,Email,MobileNo,Address,CreditScore,BankID) VALUES('Stevie Sullivan','epeeist@live.com','9630600480','Bldg No 6 Sec 10, Room No A 4, Grd Floor Nr Vijayabk, Vashi Kerala','699','9');
INSERT INTO BUYER(Name,Email,MobileNo,Address,CreditScore,BankID) VALUES('Malakai Mccullough','arathi@outlook.com','9889633771','Admn Bldg, Sheva, J N P T, Navi Mumbai','481','5');
INSERT INTO BUYER(Name,Email,MobileNo,Address,CreditScore,BankID) VALUES('Camden Bravo','bdthomas@outlook.com','6001483839','20 , Annapurna Co-op Society, Tp Road, Nardas Nagar, Bhandup(w) Ajmer','439','2');
INSERT INTO BUYER(Name,Email,MobileNo,Address,CreditScore,BankID) VALUES('Umayr Villanueva','nwiger@att.net','8075963932','Door No. 106, Patel Building, S. V. P. Road, Chinch Bunder Jaipur','343','7');
